# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '16 7 * * 0'

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
        
      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
          
  test:
      name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
         node_version: [18]
#          node_version: ['8', '10', '12']
#         os: [ubuntu-latest, windows-latest, macOS-latest]

      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      
      # TODO: Check yarn + build steps
      - name: npm install, build and test
        run: |
          npm install
          npm run build --if-present
          npm test
